// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmla4VNqG8niewGmXduOFmKLC6Z21oMp4',
    appId: '1:175502993555:web:33e9d585c4e13621dc8566',
    messagingSenderId: '175502993555',
    projectId: 'chat-app-114f9',
    authDomain: 'chat-app-114f9.firebaseapp.com',
    storageBucket: 'chat-app-114f9.appspot.com',
    measurementId: 'G-6PYN863Y18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6bjfwDB9Z-jf1fScCi9z4WirHR4B_Qkg',
    appId: '1:175502993555:android:497e673238e54a97dc8566',
    messagingSenderId: '175502993555',
    projectId: 'chat-app-114f9',
    storageBucket: 'chat-app-114f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWe4Aw0jKqz7LPUr6uFPU8_mePt1Fym8k',
    appId: '1:175502993555:ios:471ec91d5dba081cdc8566',
    messagingSenderId: '175502993555',
    projectId: 'chat-app-114f9',
    storageBucket: 'chat-app-114f9.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWe4Aw0jKqz7LPUr6uFPU8_mePt1Fym8k',
    appId: '1:175502993555:ios:7230f832b1835e4fdc8566',
    messagingSenderId: '175502993555',
    projectId: 'chat-app-114f9',
    storageBucket: 'chat-app-114f9.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
